image: docker:latest

include:
  - template: Security/SAST.gitlab-ci.yml

stages:          # List of stages for jobs, and their order of execution
  - build
  - test

services:
  - docker:dind

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - echo "CRAFTANA_TAG=${tag}" > build.env
    - docker build --pull -t "$CI_REGISTRY_IMAGE${tag}" .
    - docker push "$CI_REGISTRY_IMAGE${tag}"
  artifacts:
    reports:
      dotenv: build.env

integration-test:
  stage: test
  image: python:3.9
  services:
    - name: $CI_REGISTRY_IMAGE${CRAFTANA_TAG}
      alias: craftana
  script:
    - pip install --upgrade pip
    - pip install requests pytest
    - python -m pytest test/ --address craftana --timeout 300 --junitxml=report.xml
  dependencies:
    - build-job
  artifacts:
    when: always
    reports:
      junit: report.xml