global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          group: 'prometheus'
      - targets: ['craftana:25566']
        labels:
          group: 'craftana'

