name: craftana
main: io.github.ravidshachar.craftana.craftana
version: 1.0
commands:
    setclock:
        description: This command creates sets a clock
        usage: /setclock [ColRow] [prom socketPair] [threshold] [query]
    setgraph:
        description: This command sets a graph
        usage: /setgraph [ColRow] [prom socketPair] [step (seconds)] [threshold] [query]
    cleardashboard:
        description: This command clears the clock dashboard
        usage: /cleardashboard
    drawrect:
        description: DEV ONLY draws a rect
        usage: /drawrect [x1] [y1] [z1] [x2] [y2] [z2]
