name: craftana
main: io.github.ravidshachar.craftana.craftana
version: 1.0
commands:
    setclock:
        description: This command creates sets a clock
        usage: /setclock [ColRow] [prom socketPair] [maxValue] [query]
    setgraph:
        description: This command sets a graph
        usage: /setgraph [ColRow] [prom socketPair] [step (seconds)] [maxValue] [query]
    sethistogram:
        description: This command sets a histogram
        usage: //sethistogram [ColRow] [prom socketPair] [minValue)] [maxValue] [query]
    cleardashboard:
        description: This command clears the clock dashboard
        usage: /cleardashboard
    import:
        description: This command imports a json config file
        usage: /import [/path/to/file.json]
    export:
        description: This command exports a json config file
        usage: /export [/path/to/file.json]
    drawrect:
        description: DEV ONLY draws a rect
        usage: /drawrect [x1] [y1] [z1] [x2] [y2] [z2]
